### PR TITLE
[WIP] Added logo raw files and renderings

### PR DESCRIPTION
**Pull request by mablae**
After @Nyholm asked for ideas for a new logo on Twitter I played around a bit with a nice VoxelEditor and he seemed to like it. 

So here are all the files I produced so far:

The *.blend file can be used to re-render other angles or adjust the lightening. I am still a bit unhappy with the PHP Logo but I had no better idea about color and placement. 

So, just to have a state we could argue about, here it is :smile: 

Thanks for your patience, I learned a lot!

### CODE REVIEW

**Comment by Nyholm** [comment]
I like it. I think it looks really good. I have some questions: 
A) What rotation are we happy with? 
B) Should you read "PHP" to bottom right (like now) or top right?
C) Are that the colors from the [color scheme](http://www.cowburn.info/2015/06/18/php7-logo/)?
D) The "PHP" is now silver/gray? Does it look good if it was more white?

> Thanks for your patience, I learned a lot!

Thank you! Im happy you enjoy it.

**Comment by mablae** [comment]
@Nyholm:
A) I dont know. I can change it. 
B) Same as A)
C) I originally picked the colors from your 2nd idea. But was a washed out a bit by the lightening settings in Blender. I'll try to adjust that, to make it more like the original colors. 
D) As posted before: Any idea welcome. Maybe remove the text totally?

**Comment by cryptiklemur** [comment]
I liked it better when the text was darker (black)

**Comment by mablae** [comment]
php-cache-logo-512-flat-black

@aequasi  Here is a variant with black text and bit glossy material.

**Comment by Nyholm** [comment]
I see that you changed the order. I guess looks better with the black text on the green. I like the that it has shadows but it seams to be multiple light sources and I can't really figure out what is causing the shadow to the right.

**Comment by mablae** [comment]
@Nyholm Yeah, the glossy effect is somewhat out of place. It causes this weird shading.

**Comment by mablae** [comment]
php-cache-logo-512-flat-new-shading

I think the is the best one so far. Colors match the Scheme, and the weird shade on top is gone.

**Comment by cryptiklemur** [comment]
Looks awesome!

**Comment by Nyholm** [comment]
Yeah! Big thank you!

**Comment by mablae** [comment]
You 're welcome. If there are any questions just let me know.

**Pull request merged**
