### PR TITLE
Hierarchical implementation for Illuminate Adapter

### PR DESCRIPTION
**Pull request by Korbeil**

### CODE REVIEW

**Comment by Korbeil** [comment]
Any news ? Since the Hierarchical implementation for Illuminate Adapter PR has been merged.

**Comment by Korbeil** [comment]
@Nyholm should we merge this ?

**Comment by Korbeil** [comment]
@Nyholm update :)

**Comment by Nyholm** [comment]
Thank you

**Comment by lyrixx** [comment]
ping @Nyholm ; this is an easy pick!

**Comment by prisis** [comment]
@Korbeil thank you

**Comment by oytuntez** [comment]
The documentation on php-cache.com does not reflect this change. Now I am not sure if I can trust the documentation on the website – what is the source of truth in docs? This repo or website?

**Pull request merged**
